### PR TITLE
Add youtube and x.com support

### PR DESCRIPTION
**Pull request by Lunascaped**

### CODE REVIEW

**Comment by iCrazeiOS** [comment]
Thanks, looks good!

Would you mind building this, as I don't have a development environment right now

**Comment by Lunascaped** [comment]
i already included a built version /dist/(notracking.js)

**Comment by iCrazeiOS** [comment]
oh wow I somehow missed that after checking like three times

thanks for the PR!

**Comment by Lunascaped** [comment]
no problem!

**Pull request merged**
